trigger:
- main

pool:
  name: Default   # 👈 use your self-hosted agent pool name

steps:
# Build Step
- script: echo "Building my project..."
  displayName: "Build Step"


# Prepare second artifact (example: docs folder)
- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/docs
    echo "This is documentation" > $(Build.ArtifactStagingDirectory)/docs/readme.txt
  displayName: "Prepare Second Artifact"

# Publish second artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/docs'
    ArtifactName: 'docs'
    publishLocation: 'Container'

